kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyter-vol
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jupyter-vol
  resources:
    requests:
      storage: 10Gi